### ISSUE TITLE
Public demo 2 summary not published 

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#1049]
Public demo 2 summary https://github.com/PrestaShop/prestashop.github.io/pull/1048 not published on homepage

**Comment by matks** [comment]
fyi @kpodemski

**Comment by kpodemski** [comment]
@matks weird, I don't see any errors in the build, locally it's building fine. I've submitted one typo fix. Maybe it will somehow re-build the content and help 🤔

**Comment by matks** [comment]
Fixed https://build.prestashop.com/news/public-demo-2-2022/
