### ISSUE TITLE
1.7.8.4 release note not published

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#1055]
1.7.8.4 release note not published on https://build.prestashop.com/ although https://github.com/PrestaShop/prestashop.github.io/pull/1053 merged

**Comment by NeOMakinG** [comment]
@matks why isn't it published on build? I don't understand

**Comment by matks** [comment]
I dont know @NeOMakinG XD it's a bug

**Comment by eternoendless** [comment]
Was it merged before 6pm utc perhaps?

**Comment by matks** [comment]
@eternoendless Yes

**Comment by eternoendless** [comment]
Change the date, remove the time, it will show up

**Comment by matks** [comment]
https://github.com/PrestaShop/prestashop.github.io/pull/1056/

**Comment by matks** [comment]
@eternoendless Is it because, during build, Hugo does check what should be displayed and what should not according to current time and the items publish times?

**Comment by matks** [comment]
Published https://build.prestashop.com/news/prestashop-1-7-8-4-maintenance-release/

**Comment by eternoendless** [comment]
> during build, Hugo does check what should be displayed and what should not according to current time and the items publish times?

Build uses Jekyll, but both Jekyll and Hugo work the same way with post dates: if the date is in the future, it isn't published.
