### ISSUE TITLE
Build a tool that helps Release Product Managers to write the Patch Release Note

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#1057]
# The need

For each Patch release of PrestaShop, the release note contains the list of fixes GitHub issues.

Exemple:
```
- [Reverts the integration of Symfony kernel in the webservice dispatcher](https://github.com/PrestaShop/PrestaShop/issues/27411)
- [Update links to docs : docs.prestashop-project.org instead of doc.prestashop.com](https://github.com/PrestaShop/PrestaShop/issues/27493)
- [Fix translations installation broken by prefix](https://github.com/PrestaShop/PrestaShop/issues/27029)
- [Fix the category dropdown on the module catalog page](https://github.com/PrestaShop/PrestaShop/issues/27747)
- [Align checkboxes of multistore widget](https://github.com/PrestaShop/PrestaShop/issues/26904)
- [Fix php notices while loading subtotals](https://github.com/PrestaShop/PrestaShop/issues/27447)
- [Removed double escape for Tree Node template  to fix an error in some  BO legacy pages](https://github.com/PrestaShop/PrestaShop/issues/27616)
- [Fix the product grade not displayed in the list page](https://github.com/PrestaShop/PrestaShop/issues/27252)
- [Fix an error while adding product to cart in quantity check](https://github.com/PrestaShop/PrestaShop/issues/27505)
- [Remove duplicate shopping carts and  make sure carts are linked](https://github.com/PrestaShop/PrestaShop/issues/27450)
- [Fix Entities Mapping error on debug mode](https://github.com/PrestaShop/PrestaShop/issues/27218)
```

The list is structured as a Markdown list : `- [...](...)`

@fabienvallon would like to build a tool that helps Release Product Managers to generate this list.

# Input and output

The tool should be a command-line php script that can be run to generate the list.

Example: running `php my-tool.php 1.7.7.1 > mylist.md` should output inside mylist.md the list of the fixes issues inside 1.7.7.1 release patch.

**Given** a milestone (example: 1.7.7.1, 1.7.8.2, 1.7.8.4)
**Then** the list of GitHub issues _with label "Fixed"_ and _milestoned with given milestone_
should be printed out, the list follows Markdown list format

Each list item contains the issue title inside `[]` then the GitHub link inside `()`

## Acceptance test

**Given** milestone 1.7.8.2
**Then** the [list of fixed 1.7.8.2 issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AFixed+milestone%3A1.7.8.2+is%3Aclosed)
should be printed:
```
- [Wishlist button disappears while using Faceted Search](https://github.com/PrestaShop/PrestaShop/issues/26327)
- [Missing Alias CustomerQueryBuilder.php](https://github.com/PrestaShop/PrestaShop/issues/23394)
```

# Help references

- Symfony Command Line console documentation https://symfony.com/doc/current/console.html
- I built a few command line php scripts for PrestaShop on https://github.com/matks/prestashop-repos-bulk-editor you might use them as examples
- PrestaShop organization has 2 command line php tools: https://github.com/prestashop/presthubot and https://github.com/prestashop/php-dev-tools
- 1.7.8.4 release note on Build blog https://build.prestashop.com/news/prestashop-1-7-8-4-maintenance-release/
- 1.7.8.4 release note Pull Request https://github.com/PrestaShop/prestashop.github.io/pull/1053/

You might be able to use GitHub API without needing an authentication token (some API endpoints are public, some need to be authenticated). If a token is needed, the CLI tool should accept the token as an option (example `php my-script.php --token=jdsjisdjiosdjiosdjiodsjoid 1.7.8.2`)

**Comment by fabienvallon** [comment]
Fixed or Done ?

**Comment by Progi1984** [comment]
A job for presthubot ?

**Comment by matks** [comment]
@Amoifr started exploring options for this one 😉

**Comment by Amoifr** [comment]
@Progi1984 when my code will be ready I will enjoy to know where presthubot is located and how to contribute.

**Comment by Progi1984** [comment]
@Amoifr https://github.com/PrestaShop/presthubot

You have a lot of services for the Github API already used for the Slack Bot (for example).

**Comment by Amoifr** [comment]
@Progi1984 : thx !

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/presthubot/pull/49

ping @PrestaShop/product-team 😉
