### ISSUE TITLE
Disqus comments erased?

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#1177]
I cannot see any Disqus comments on https://build.prestashop-project.org/

@eternoendless @kpodemski 

Maybe related to https://github.com/PrestaShop/prestashop.github.io/issues/620

**Comment by kpodemski** [comment]
Oh, right, URL structure is now different after migrating to Hugo.

**Comment by eternoendless** [comment]
Oh I forgot about that detail, it's related to the URLs being changed
