### ISSUE TITLE
Link Crowdin guide in "Do you speak PrestaShop articles?"

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/prestashop.github.io#1246]
I noticed that in the "Do you speak PrestaShop?" series, we don't have a link to the documentation explaining how to translate PrestaShop there. I think it'd be great to add it somewhere in a visible place.

https://docs.prestashop-project.org/translating-prestashop/

**Comment by kpodemski** [comment]
wdyt @Julievrz @l-delin ?

**Comment by l-delin** [comment]
Hello @kpodemski, I think that's a great idea. :-) Perhaps we could add it to the "Let's keep in touch" section and edit it a bit. I'll add it to the next Crowdin Monthly, which should be published soon.
