### ISSUE TITLE
video users testing not available

### ISSUE THREAD

**Issue by prestarocket** [PrestaShop/prestashop.github.io#139]
the youtube video is only viewable on youtube 
<img width="614" alt="capture d ecran 2016-03-21 a 20 25 51" src="https://cloud.githubusercontent.com/assets/899422/13931378/50113134-efa3-11e5-89e6-7db0e287bd22.png">

**Comment by xBorderie** [comment]
Yup, fixed, bad setting on YouTube :)
Thanks!
