### ISSUE TITLE
404 Link in article 

### ISSUE THREAD

**Issue by AliShareei** [PrestaShop/prestashop.github.io#352]
Hello dear! 

on this Article
http://build.prestashop.com/news/prestashop-1-7-3-0-rc-1/

has an 404 link to
http://build.prestashop.com/news/how-to-create-bug-report/

mybe this link must be use!
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Regards,

**Comment by eternoendless** [comment]
Thanks @AliShareei, we'll have a look!

**Comment by LouiseBonnard** [comment]
@AliShareei, thanks for the report, I've just corrected it. ;-)
