### ISSUE TITLE
Contribute guide is outdated

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#546]
http://build.prestashop.com/howtos/misc/contribute-to-prestashop/
The PDF guide provided is a bit outdated, some informations are now accurate anymore.

**Comment by matks** [comment]
We could redirect to https://devdocs.prestashop.com/1.7/contribute/ instead but there are a few sections not covered by the devdocs that were covered by the PDF Guide

**Comment by eternoendless** [comment]
Fixed
