### ISSUE TITLE
[Article suggestion] Software lifecycle

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#549]
Should we write an article that explains the new lifecycle now ? With 1 month beta period and release candidates ?

This could be used to answer "when will PS 1.7.x be released" ? 😄

**Comment by matks** [comment]
@samuel-pires You gave a presentation about it yesterday, do you feel like writing an article 😄 ?

**Comment by ttoine** [comment]
+1
you can also use your slides in the article, and write content around

**Comment by ghost** [comment]
Well, alright I can give it a shot.
Which audience should it be written for?


What about the releases frequency? should it be mentioned?

**Comment by ttoine** [comment]
yes, you can mention it.
target freelancers, techs people in agencies, module & themes developers, so they can schedule migrations with their customers
