### ISSUE TITLE
[Article Suggestion] New Release notes format

### ISSUE THREAD

**Issue by ghost** [PrestaShop/prestashop.github.io#553]
The idea is to write an article about our new communication process for the releases (once it's done).

It might be interesting to share our new process and different types of information available to our community.

Is is also a good way to get feedback about it.

I'm ok to write it or co-write it ✋

**Comment by ttoine** [comment]
ok !

**Comment by matks** [comment]
I think writing this now is not relevant anymore 😅  and the new releases note format has been adopted
