### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#556]

**Comment by PierreRambaud** [comment]
https://help.github.com/en/articles/securing-your-github-pages-site-with-https :)

**Comment by ttoine** [comment]
une idée de comment on peut tester ça sans tout péter, et roll back si besoin ? car on utilise une vieille version de Jekyll.

**Comment by matks** [comment]
@ttoine A priori, pas lié à Jekyll. C'est lié à la config DNS du site, qui est gérée par github. Pas possible de tester avant, mais c'est github je pense on peut avoir confiance

**Comment by ttoine** [comment]
unfortunately, it seems that I don't have the right to manage that. Maybe @eternoendless can?

**Comment by matks** [comment]
Fixed ✅
