### ISSUE TITLE
Build blog has 2 identical canonical tag in the header

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/prestashop.github.io#569]
![image012](https://user-images.githubusercontent.com/4619685/63704668-cd002b00-c82b-11e9-974a-8629326b1100.png)

As you can see, the "canonical" tag is generated twice. We need to find why it is duplicated and then, remove the second one.

**Comment by sam-pires** [comment]
I checked, indeed we have a duplicate, here is why
- The first one is generated by the [jekyll-seo-tag plugin](https://github.com/jekyll/jekyll-seo-tag)
- The second one is generated by Jekyll itself

It is not a problem as long as they are identical. But if they are different it becomes a "potential" issue according [to this Sitebulb article](https://sitebulb.com/hints/indexability/multiple-canonical-tags/).

If we decide to remove it here is my recommendation:

The canonical generated by the jekyll-seo-tag can be customized in the front matter, whereas the Jekyll default one cannot -> it's an interesting feature.
Moreover, it is easier to remove the Jekyll canonical tag in the page template.
Then, if we decide to delete one, I suggest keeping the jekyll-seo-tag one.

The Jekyll default canonical tag is accessible in this file `/prestashop.github.io/_includes/head.html`

**Comment by sam-pires** [comment]
PR available @ttoine 👇
