### ISSUE TITLE
The logo as no "alt" tag and is not a H1

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/prestashop.github.io#571]
In order to improve the SEO of the blog, two improvements are required:
- add an "alt" description in the img tag, so the logo can be associated to text for search engines
- the blog page is currently missing a H1 title, and like many blog, it would be great to add it to the logo (the title being interpreted from the "alt" description)

**Comment by sam-pires** [comment]
Hi @ttoine 
I just stumbled upon this issue. It seems to be fixed already 🙂 

- Images already have an "alt" tag
- The title of the post is an h1

Did I miss something?

**Comment by ttoine** [comment]
![Selection_568](https://user-images.githubusercontent.com/4619685/69954572-e9cb8f00-14fb-11ea-81c3-ee7ad2f2ca03.png)

I should have added this screenshot in the bug report.

**Comment by ttoine** [comment]
btw this is something we should be able to fix easily in the template.

**Comment by sam-pires** [comment]
Ok I thought it was in posts pages, not in the list 👍

**Comment by ttoine** [comment]
![Selection_570](https://user-images.githubusercontent.com/4619685/69955698-8b53e000-14fe-11ea-8e56-5aac58e932ac.png)

if you look in a post, you will see that the blog logo is not a H1.
and the H1 is the title of the blog post. that's not a best practice.
but changing that would mean editing the CSS.
there is a relative bug also: the subtitle, in the list and in the blog post, is a H3... it should have a dedicated class and should not be a H...

**Comment by sam-pires** [comment]
In a post I believe it is a best practices to have the title as the h1.

I also believe the subtitlte should be a h, but not a h3, rather a h2.

We could ask Flavia about it :)

**Comment by ttoine** [comment]
she actually reported the problems to and then I create issues here.

see #573

**Comment by Sinepel** [comment]
Hi everyone ! 
I just did a PR that adds an alt on the logo + H1 on the home page!
