### ISSUE TITLE
[Article suggestion] Best posts from 2019

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#630]
@sam-pires I believe you have access to analytics, maybe we could write a "Best of posts from 2019" ?

**Comment by sam-pires** [comment]
@ttoine do you want to do it?

**Comment by ttoine** [comment]
my feeling is that best posts of 2019, most people already read them so it it really useful?

what about highlighting less visited information, or maybe stuff that are not on Build, too? that could be on other blogs too, like Symfony's project, or other things we use for PrestaShop

**Comment by matks** [comment]
> my feeling is that best posts of 2019, most people already read them so it it really useful?

It's useful for people who did not read the blog in 2019 and started following it in 2020. Or people who read blogs in beginning and end of 2019 but for personal reasons did not read it in the middle.
