### ISSUE TITLE
Markdown bottom page references do not work

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#670]
This does not work on Build:
```
Lorem ipsum[1]
Lorem ipsum
Lorem ipsum

[1]: reference
```

**Comment by matks** [comment]
See https://build.prestashop.com/news/ps17-minor-release-lifecycle/ (before I fix it)
<img width="820" alt="Capture d’écran 2020-03-24 à 14 08 07" src="https://user-images.githubusercontent.com/3830050/77428855-0ce6bb00-6dd9-11ea-9743-ae16fbdb5260.png">

**Comment by PrestaEdit** [comment]
Hi @matks ,

As the pull request made for this is merged, is still open ?

**Comment by matks** [comment]
@PrestaEdit No the PRs are referencing this issue but they do not fix the problem

**Comment by eternoendless** [comment]
FYI that is a link, not a footnote. Footnotes are used like this:

```
Lorem ipsum[^1]
Lorem ipsum
Lorem ipsum

[^1]: this is a footnote
```

I have verified this to work as expected since we use Hugo.
