### ISSUE TITLE
Meta image is the author on bottom "other articles" slider

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#707]
On https://build.prestashop.com/news/coreweekly-18-2020/ at the bottom there is a slider of other articles.
Looks like meta image used for https://build.prestashop.com/news/ps17-patch-release-lifecycle/ is ... my face 😄because I'm the author.

I appreciate but is it the best image ? I'm not sure

<img width="1151" alt="Capture d’écran 2020-05-21 à 15 46 07" src="https://user-images.githubusercontent.com/3830050/82565142-340ffd80-9b7a-11ea-8873-ad1e58720127.png">

**Comment by matks** [comment]
It seems the image is used because there is no "top image", contrarily to most other articles.

**Comment by sam-pires** [comment]
yep, when no meta image is added in the front-matter it uses the author's avatar image.
I'm on it ;)

**Comment by sam-pires** [comment]
I didn't know Disqus was pushing other articles now btw, that's great!
