### ISSUE TITLE
Core weekly 20 of 2020 appears higher than core weekly 21 of 2020

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#712]
https://build.prestashop.com/

**Comment by matks** [comment]
This might be because Markdown file for core 20 is wrong:
`https://github.com/PrestaShop/prestashop.github.io/blob/master/news/_posts/core-weekly/2020-25-05-coreweekly-20-2020.md`
⏬ 
`https://github.com/PrestaShop/prestashop.github.io/blob/master/news/_posts/core-weekly/2020-05-25-coreweekly-20-2020.md`

**Comment by ttoine** [comment]
it's actually because there are only a date, and no hour in the header.
