### ISSUE TITLE
Show articles written by the same author when clicking on authors' profile 

### ISSUE THREAD

**Issue by Junebyun** [PrestaShop/prestashop.github.io#763]
When an article is written on https://build.prestashop.com/ the name and role of the author is shown at the left side below "_Written by_" and "_About the author_" at the end of the article. 

**Suggestion**
It would be nice to show the list of articles written by the same authors once you click on its profile picture or name. :)

**Comment by Sinepel** [comment]
I'd like to do it, I'll take care of it as soon as I have time if it suits you :)

**Comment by ttoine** [comment]
that would be a interesting improvement !

**Comment by Sinepel** [comment]
Hello, 

I started, I manage to get the author pages, but not yet to propose a pagination. For the moment, no pagination, as for the page tags. Is it a problem?

**Comment by ttoine** [comment]
would you share a screenshot ?

**Comment by eternoendless** [comment]
I'm happy to announce that this has been done! Now you can easily brag about your articles :)
