### ISSUE TITLE
Lot of tags that are not properly registered

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#813]
It seems that tags need to be registered in 2 places to work:
- https://github.com/PrestaShop/prestashop.github.io/blob/master/_data/tags.yml
- https://github.com/PrestaShop/prestashop.github.io/tree/master/tag

If tags exist in https://github.com/PrestaShop/prestashop.github.io/blob/master/_data/tags.yml they are clickable but lead to an http 404 page.
If tags exist in https://github.com/PrestaShop/prestashop.github.io/tree/master/tag they are not clickable but the "tag" page work.

So tags must simply be registered in both places to work. However I found many articles, even recent, that use unregistered tags.

I fixed the most important ones in https://github.com/PrestaShop/prestashop.github.io/pull/812

**Comment by ttoine** [comment]
oooh brilliant !

**Comment by eternoendless** [comment]
I'm under the impression that this is no longer an issue.
