### ISSUE TITLE
Provide default image metadata

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#817]
There is no default `og:image` property. This results in poor preview on social networks:

<img width="579" alt="Capture d’écran 2020-12-08 à 23 51 42" src="https://user-images.githubusercontent.com/3830050/101693390-d4276880-3a71-11eb-8bca-84c630e91d03.png">

We should provide a default `og:image` property on all page and allow each page to override it.

The result would look like

<img width="615" alt="Capture d’écran 2020-12-09 à 00 12 35" src="https://user-images.githubusercontent.com/3830050/101693527-089b2480-3a72-11eb-9ec0-f75374b7c375.png">

Actually `jekyll-feed` plugin is enabled so pages with `image` property have an `og:image`.

So the spec for this idea is "when there is no `og:image` tag provided by jekyll-feed, add one with default Build image"

**Comment by ttoine** [comment]
+1
I guess it needs a modification of the templates? and what about articles where we put a meta picture? how to handle that wel?
