### ISSUE TITLE
Archive old blog posts

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#868]
@PierreRambaud is worried that the continuous adding of new files inside this repository will
- make the navigation inside the folders harder
- one day hit the maximum files limit of a folder

One solution would be to archive old blog posts into year/month subfolder.

```
posts
-- core-weekly
---- 2018
------ 01
------ 02
```

**Comment by matks** [comment]
wdyt @eternoendless

**Comment by eternoendless** [comment]
The hard limit is about ~65k files, we're very, very far away from hitting that.

Moving old posts into subfolders would break existing URLs (unless we take care of manually rewiring them through redirections), and also I think it might make those articles disappear from the home listing (but I might be wrong about that last part).

**Comment by PierreRambaud** [comment]
The limit depends on the system behind, can be 20k, but yes we are far away from it.

But, we should do something to reorganize posts, even if we have to add RedirectPermanent, currently we have posts in these directories:
- https://github.com/PrestaShop/prestashop.github.io/tree/master/howtos
- An empty directory https://github.com/PrestaShop/prestashop.github.io/tree/master/how-tos
- https://github.com/PrestaShop/prestashop.github.io/tree/master/tools/_posts
- https://github.com/PrestaShop/prestashop.github.io/tree/master/news/_posts
- and in many directories inside the last one.
