### ISSUE TITLE
[Public OSS Demo] Offer an alternative to YouTube for viewers?

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#889]
Following a blog post on [LinuxFR](https://linuxfr.org/news/prestashop-diffuse-chaque-mois-les-avancees-du-projet-sur-youtube) we've had [feedbacks](https://linuxfr.org/nodes/124052/comments/1850927) about using YouTube as a platform for an open source project. Indeed YouTube is not close to open source and free software.

I think YouTube offers a good (maybe the best) compromise between easy-to-use, traffic capabilities, price, worldwide-known and availability. I dont think we should stop using it. However it can be considered relevant to provide a 2nd way for users who do not wish to use YouTube to watch or download the videos.

I see 2 possible ways
- Jitsi allows me to connect a RMTP stream to many platforms. Currently I only stream to YouTube. I could stream to another endpoint, in a streaming platform closer to open source
- Host the replays on a free platform on a PrestaShop server

**Comment by matks** [comment]
Looking for feedbacks @eternoendless @ttoine @kpodemski @PululuK 😃

**Comment by eternoendless** [comment]
I definitely think it isn't worth our time.

**Comment by kpodemski** [comment]
I think we should aim to provide easiest way of access to live stream and video after it, I know that here we care about open source, but let's not go to the extreme... maybe it would be enough to provide URL to download video?
