### ISSUE TITLE
Generated Core Weekly 30 contains github data from week 31 

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#944]
https://github.com/PrestaShop/prestashop.github.io/pull/943 contains github data from week 31 although it is the Core Weekly 30

**Comment by matks** [comment]
I reopen, waiting for next Core Weekly to validate it works as expected

**Comment by PierreRambaud** [comment]
We are maybe able to redo the job on the previous Core Weekly?

**Comment by matks** [comment]
@PierreRambaud we need to enable the workflow to be triggered manually
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Comment by matks** [comment]
Fixed. Confirmed by Core Weekly 34 generated this morning.
